# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  melody.boutique:
    site_hosts:
      - canonical: melody.boutique
        redirects:
          - melody.boutique
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:darrenlzh/melody-fashion-wp.git
    repo_subtree_path: site
    branch: master
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
